export const projects = [
  {
    title: "Agentic TODO",
    description: `AI-powered Flutter task manager with Firebase sync, smart scheduling, recurring tasks, habit streaks, Pomodoro sessions, and OpenRouter model support.`,
    href: "https://github.com/justaman045/Agentic-TODO",
    mediaSrc: "/2.jpg",
    mediaType: "image",
  },
  {
    title: "Finance Control",
    description: `Flutter personal finance app with expense tracking, wealth management, biometric lock, offline-first flows, Firebase, and release automation.`,
    href: "https://github.com/justaman045/Finance-Control",
    mediaSrc: "/3.jpg",
    mediaType: "image",
  },
  {
    title: "Assistant",
    description: `Personal productivity SaaS built with Next.js, Firebase, OpenRouter, Razorpay, memory, prompt library, planner, finance tracking, and admin tooling.`,
    href: "https://github.com/justaman045/Assistant",
    mediaSrc: "/4.jpg",
    mediaType: "image",
  },
  {
    title: "SaaS Waitlist",
    description: `Reusable waitlist product for collecting launch signups, managing projects, referrals, emails, images, and public project pages.`,
    href: "https://github.com/justaman045/Saas-Waitlist",
    mediaSrc: "/5.jpg",
    mediaType: "image",
  },
  {
    title: "CodeitDown",
    description: `API-driven Next.js blog frontend focused on SEO, content discovery, categories, tags, search, and clean publishing workflows.`,
    href: "https://github.com/justaman045/codeitdown",
    mediaSrc: "/6.jpg",
    mediaType: "image",
  },
  {
    title: "Instagram Content Analyzer",
    description: `Python CLI automation framework for Instagram workflows with scheduling, persistence, modular integrations, and safety-focused usage notes.`,
    href: "https://github.com/justaman045/Instagram-Content-Analyzer",
    mediaSrc: "/7.jpg",
    mediaType: "image",
  },
  {
    title: "Job Application Tracker",
    description: `React/Firebase tracker for applications, interviews, offers, kanban workflows, exports, PWA support, and job-search analytics.`,
    href: "https://github.com/justaman045/Job-Application-tracker",
    mediaSrc: "/8.jpg",
    mediaType: "image",
  },
];
