export const projects = [
  {
    title: "Athena",
    description: `Secret Blog and Digital Garden for the online world`,
    href: "https://athenabyaman.vercel.app",
    mediaSrc: "/2.jpg",
    mediaType: "image",
  },
  {
    title: "Portfolio",
    description: `A personal Portfolio website developed with Nextjs and Tailwind CSS for showcasing all of my Online work.`,
    href: "https://coderaman7.vercel.app",
    mediaSrc: "/3.jpg",
    mediaType: "image",
  },
  {
    title: "Auto Poster",
    description: `A Cross Platform Desktop App client to post updates to social media platforms from one Place`,
    href: "https://github.com/coderaman7/Auto-Poster",
    mediaSrc: "/4.jpg",
    mediaType: "image",
  },
  {
    title: "RedBot",
    description: `A Cross Platform Desktop App client to use Reddit from Desktop system only without opening any browser with a clean UI`,
    href: "https://github.com/coderaman7/RedBot",
    mediaSrc: "/5.jpg",
    mediaType: "image",
  },
  {
    title: "CodeitDown",
    description: `A web App for showcasing all the blogs written by a me`,
    href: "https://github.com/coderaman7/codeitdown",
    mediaSrc: "/6.jpg",
    mediaType: "image",
  },
  {
    title: "Content Manager",
    description: `This Project is a Blog Manager for a Blogger ( particularly Tech Blogger ), this project will post your Stories and Blogs on selected platforms without even opening browser using API keys.`,
    href: "https://github.com/coderaman7/Content-Manager",
    mediaSrc: "/7.jpg",
    mediaType: "image",
  },
  {
    title: "Django E-commerce Website",
    description: `E - Commerce Website Built in Django with admin features to run your Ecommerce Platform in minutes.`,
    href: "https://github.com/coderaman7/Django-ECommerce-Website",
    mediaSrc: "/8.jpg",
    mediaType: "image",
  },
];
